### ISSUE TITLE
Can this project work for single image deblurring?

### ISSUE THREAD

**Issue by Darrenxc** [csbhr/CDVD-TSP#1]
hi, 
your work is great.
I just wonder can this project work for single image deblurring?
thank you

**Comment by csbhr** [comment]
Thanks for your attention！
The main contribution of our work is to focus on the use of temporal information in videos. Video sequences are required for both the optical flow estimation and temporal sharpness prior. For this reason, the advantages of our work cannot be reflected in image deblurring.

**Comment by jspan** [comment]
> hi,
> your work is great.
> I just wonder can this project work for single image deblurring?
> thank you

You can of course use our code to deblur single images. For such case, the optical flow, temporal sharpness prior will have no effect but the proposed cascaded training approach still help image deblurring

**Comment by Darrenxc** [comment]
Thank you!
