### ISSUE TITLE
Requirement.txt

### ISSUE THREAD

**Issue by Michaelwhite34** [csbhr/CDVD-TSP#14]
Hi,I managed to run the project but I cann't run it now after reinstalling OS.I installed all the dependency but always get error like no module name torch.. Someone provides a requirement.txt, plz.

**Comment by YellowOrz** [comment]
You need to install pytorch.  You can refer to its official website about installation https://pytorch.org/get-started/locally/

**Comment by jpiabrantes** [comment]
Which torchvision version to use? The most up-to-date is not compatible with pytorch=0.4.1

**Comment by csbhr** [comment]
From the following link, you can download a "requirements.txt" file, which is exported from the anaconda environment I used.

https://drive.google.com/file/d/1sMyWxRscndc-lUTbbsekeiIpOs16bwya/view?usp=sharing

**Comment by jpiabrantes** [comment]
Trying to use that `requirements.txt`:

```sh
> conda create -n deblur --file requirements.txt 

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - torchvision==0.2.1=py_2
  - pytorch==0.4.1=py36_py35_py27__9.0.176_7.1.2_2

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
