### ISSUE TITLE
A Super parameter

### ISSUE THREAD

**Issue by jianjiandandande** [csbhr/CDVD-TSP#18]
https://github.com/csbhr/CDVD-TSP/blob/a9bfcae1c369a0444d5ccb900ff91681a4b82f31/code/option/template.py#L6

What does this superparameter do, I feel that the number of image frames in each category is not exactly equal to this value

**Comment by csbhr** [comment]
This hyper-parameter sets an upper limit on the number of frames used for each video sequence.

If the number of frames in the training sequence is greater than 100, we only take the first 100 frames for training.
