### ISSUE TITLE
On which machine the network was learned?

### ISSUE THREAD

**Issue by agnieszkajust** [csbhr/CDVD-TSP#19]
I am trying to learn the network on gpu (RTX 2060) with batch = 1 but the computer starts humming and turns off. On which machine the network was learned? Can I change some parameter to the training on my computer starts correctly?

**Comment by csbhr** [comment]
We trained the network on TITAN RTX whose GPU memory is 24G.

**Comment by csbhr** [comment]
You can take a smaller patch-size, but the performance may be limited.

**Comment by agnieszkajust** [comment]
In other computer I have installed cuda 11.0. When I was running training network I got "AttributeError: module 'cupy' has no attribute 'util'". Do I have to install other drivers and cude to run training?

**Comment by agnieszkajust** [comment]
I solve it.
