### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yustiks** [csbhr/CDVD-TSP#22]
I try to run the code and I have the following error:
```
Inference - 2021-05-17 03:42:15
save_image: True
border: False
model_path: model/CDVD_TSP_DVD_Paper.pt
data_path: data/dataset/
result_path: ../infer_results
n_seq: 5
size_must_mode: 4
device: cuda
Creating CDVD-TSP Net
Is meanfilter image when process mask: True
Select mask mode: concat, num_mask=1
Creating Flow PWC
Creating Recons-Video Net
SRN Video Net extra in channels: 1
The input of SRN is image
Loading model from model/CDVD_TSP_DVD_Paper.pt
Traceback (most recent call last):
  File "inference.py", line 243, in <module>
    Infer.infer()
  File "inference.py", line 123, in infer
    self.logger.write_log("# Total AVG-PSNR={:.5}, AVG-SSIM={:.4}".format(sum_psnr / n_img, sum_ssim / n_img))
ZeroDivisionError: float division by zero
```

What can be the reason?

**Comment by csbhr** [comment]
This is because that your dataset does not load correctly.

Please check your dataset path and the organization form of the dataset.

**Comment by yustiks** [comment]
I create the dataset accordingly, and now I have another issue: only one image is restored, all the other images are not considered by the method. 
What could be the reason?

**Comment by csbhr** [comment]
The model takes 5 blur frames as inputs and restores 1 deblurred frame. This inference code does not consider the border frames at the beginning and end of the video sequence.

You can copy the border frames to make this code consider border frames.

**Comment by csbhr** [comment]
For example:

burry frames [1, 2, 3, 4, 5] -> deblurred frames [3]

copy the border frames:
burry frames [1, 1, 1, 2, 3, 4, 5, 5, 5] -> deblurred frames [1, 2, 3, 4, 5]
