### ISSUE TITLE
how to download PWC-Net pre-trained model?

### ISSUE THREAD

**Issue by ghost** [csbhr/CDVD-TSP#27]
Hi , your work is very good. But I do not know how to download the PWC-Net pre-trained model when I try to train your network. Can you tell me ? Thanks a lot!

**Comment by csbhr** [comment]
The pre-trained PWC-Net model (download from [sniklaus/pytorch-pwc]) used in the training process is included in the following link and the filename is "pretrain_models/network-default.pytorch"

https://drive.google.com/drive/folders/1lw_1jITafEQ9DvMys_S6aYwtNApYKWsz?usp=sharing

**Comment by ghost** [comment]
谢谢！
