### ISSUE TITLE
how to change the maximum frames of single vedio ?

### ISSUE THREAD

**Issue by ghost** [csbhr/CDVD-TSP#29]
您好！想请问一下您，每个video内的帧数最多只能是100吗？这个限制应该在哪个文件里面修改呢？我在一个video文件里装了5k张图片，但是程序显示只读取了100张图片。谢谢您的解答！

Hello! Could you please tell me that the maximum number of frames in each video is 100? In which file should this restriction be changed? I have packed 5K pictures in a video file, but the program shows that only 100 pictures have been read. Thank you for your answer!

**Comment by Etienne66** [comment]
I don't recall having that limit when just debluring my own video but during training there is a parameter set to 100.

In `code\option\template.py` change the `n_frames_per_video` to whatever value you want.

**Comment by ghost** [comment]
thank you very much!
