### ISSUE TITLE
The algorithm is supervised or unsupervised?

### ISSUE THREAD

**Issue by ghost** [csbhr/CDVD-TSP#30]
The ground truth image is only used for calculate SSIM?  Does Igt have any other functions? What does the Igt do in equation (13)?

您好！请问这个算法是有监督还是无监督的啊，gt只是用来计算SSIM的吗？Igt就是数据集中输出的gt图像吗，公式（13）中的Igt的用途是什么呢？谢谢，打搅您了！
![Uploading image.png…]()

**Comment by Etienne66** [comment]
If you are just testing it with your own images then the ground truth image is just used to calculate the PSNR and SSIM. My version doesn't require ground truth images for testing and will simply skip that calculation if it doesn't find any ground truth folders.

If you are training it instead then you need ground truth images.

**Comment by csbhr** [comment]
这个方法是有监督的方法，需要使用GT进行训练。
但测试的时候，GT仅用于计算PSNR/SSIM。
