### ISSUE TITLE
Can you share your training logs?

### ISSUE THREAD

**Issue by yuanze-lin** [csbhr/CDVD-TSP#31]
Hi, dear authors, can you share your training logs on Gopro dataset?

**Comment by Etienne66** [comment]
The way I'm reading the paper and the code, they did not train it on GoPro data. They trained it on the DVD data and simply used the test set from GoPro to compare the results with those other papers.

**Comment by yzleroy** [comment]
If I train proposed method on DVD dataset, and I find one epoch will take more than 1 hour (I use 4 x P40). But training epochs are 500. The whole training time will take several weeks. I think it's too long.
