### ISSUE TITLE
What datasets did the model(s) use for training?

### ISSUE THREAD

**Issue by vlee-harmonicinc** [csbhr/CDVD-TSP#6]
There are 3 video deblurring datasets. DVD(Deep video deblurring for hand-held cameras), GOPRO (from Deep multi-scale convolutional neural network for dynamic scene deblurring) and REDS (NTIRE 2019)

What datasets did the released pretrained model use for training? 
Also what datasets did the EDVR (Quantitative evaluations) train on?
Did you test CDVD-TSP result on REDS dataset?

**Comment by csbhr** [comment]
The pretrained models "CDVD_TSP_DVD_Convergent.pt" and "CDVD_TSP_DVD_Paper.pt" are trained on DVD dataset. The pretrained model "CDVD_TSP_GOPRO.pt" is trained on GOPRO dataset.

The EDVR's quantitative evaluations are achieved by using its provided pretrained model.

Our results on REDS dataset did not exceed EDVR, but we noticed that EDVR is overfitted on REDS dataset and it does not perform well on real datasets.

**Comment by vlee-harmonicinc** [comment]
Thank you for the quick respond :)
The GOPRO one produce obvious artifact on my testing video, probably because the datasets is too small. Result of CDVD-TSP trained DVD is much better.
Nice work :)
