### ISSUE TITLE
The gap between inference results and the reported reuslts in paper

### ISSUE THREAD

**Issue by ZYzhouya** [csbhr/CDVD-TSP#7]
hi, your work is great！But I wonder why there is a gap between inference results (about 28.4db on GOPRO) using the provided pretrained model and the reported reuslts (31.67db) in paper?

**Comment by csbhr** [comment]
Thanks for your attention.
If you want to test on GOPRO dataset, please make sure that it uses the pretrained model named "CDVD_TSP_GOPRO.pt".

**Comment by ZYzhouya** [comment]
> Thanks for your attention.
> If you want to test on GOPRO dataset, please make sure that it uses the pretrained model named "CDVD_TSP_GOPRO.pt".

Thanks for your reply: )！For GOPRO dataset, I'm sure I use "CDVD_TSP_GOPRO.pt", and for DVD dataset, I use "CDVD_TSP_DVD_Convergent.pt" which also cannot obtain the reported results.

**Comment by csbhr** [comment]
I just re-downloaded the GOPRO test dataset and the pretrained model from the given link "https://drive.google.com/drive/folders/1lw_1jITafEQ9DvMys_S6aYwtNApYKWsz?usp=sharing". 

And, I ran the commands:
cd ./code
python inference.py --default_data GOPRO

Then, I got the same results reported in the paper.
So, please make sure that you followed the "https://github.com/csbhr/CDVD-TSP#quick-test" steps in the README.

**Comment by ZYzhouya** [comment]
> I just re-downloaded the GOPRO test dataset and the pretrained model from the given link "https://drive.google.com/drive/folders/1lw_1jITafEQ9DvMys_S6aYwtNApYKWsz?usp=sharing".
> 
> And, I ran the commands:
> cd ./code
> python inference.py --default_data GOPRO
> 
> Then, I got the same results reported in the paper.
> So, please make sure that you followed the "https://github.com/csbhr/CDVD-TSP#quick-test" steps in the README.

Thanks for your efforts!

I use the below command to test the performance previously：
python main.py --dir_data ../dataset/GOPRO/train --dir_data_test ../dataset/GOPRO/test --epochs 1 --batch_size 8 --test_only --pre_train ../pretrain_models/CDVD_TSP_GOPRO.pt

And following your last reply, I have retested the performance on the two datasets again using the quick-test commands you recommend. But I still can't obtain the reported performance (only about 28.+dB).

**Comment by csbhr** [comment]
You can try to re-download the codes, test datasets and pretrained models.
Then run the commands again:
cd ./code
python inference.py --default_data GOPRO

**Comment by csbhr** [comment]
Here is the inference log on GOPRO dataset, that I tested last night.
https://drive.google.com/file/d/1nMDERzlZRgkszPZcl8kIlFTf0CPQj824/view?usp=sharing

**Comment by ZYzhouya** [comment]
> You can try to re-download the codes, test datasets and pretrained models.
> Then run the commands again:
> cd ./code
> python inference.py --default_data GOPRO

I re-download the codes and re-test the performance again. Finally obtain the results:
Total AVG-PSNR=28.565, AVG-SSIM=0.8746
So it seems a little strange. Whether you modify the codes after releasing the work or use another pretrained model to test？

**Comment by csbhr** [comment]
Again, I downloaded the codes, pre-trained models and test dataset.
I did not modify anything, just ran the commands:
cd ./code
python inference.py --default_data GOPRO

Then, I got the same results reported in the paper.
Please check whether there is something wrong with your operation.
